/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package authservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication
public class App {
    public static void main(String[] args) {
        //System.out.println("Starting application...");
        SpringApplication.run(App.class, args);
    }
}
